In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '16'

In [7]:
from sufield.datasets import get_transform
import yaml
with open('/home/tb5zhh/SUField/config.yaml') as f:
    a = f.read()
args =  yaml.load(a, yaml.Loader)['training']
get_transform(args['transforms'])

In [1]:
from sufield.datasets.dataset import ScanNetVoxelizedDataset
import sufield.datasets.transforms as t
import numpy as np
dataset = ScanNetVoxelizedDataset(
    '/home/tb5zhh/SUField/datasets/ScanNetv2_train_data.txt',
    '/home/tb5zhh/SUField/datasets/ScanNetv2_train_labels.txt',
    return_paths=True,
    transforms=t.Compose([
        t.ToTensor(),
        t.ElasticDistortion(((0.2, 0.4), (0.8, 1.6)), 1),
        t.RandomRotation(((0,0),(0,0),(np.pi/2, np.pi/2)), 1),
        t.RandomScaling((0.1, 1.1), 1),
        t.NonNegativeTranslation(1),
        t.Voxelize(),
        t.RandomDropout(0.5, 1),
        t.RandomHorizontalFlip('z', [1, 1], 1),
        t.ChromaticAutoContrast(apply_ratio=1),
        t.ChromaticTranslation(0.1, apply_ratio=1),
        t.ChromaticJitter(0.05, apply_ratio=1),
        # t.HueSaturationTranslation(0.5, 0.2)
    ]),
)

/home/tb5zhh/.conda/envs/sufield/lib/python3.8/site-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(


In [2]:
from torch.utils.data import DataLoader

In [3]:
dataloader = DataLoader(dataset,
                            batch_size=4,
                            num_workers=1,
                            collate_fn=t.cf_collate_fn_factory(250000))

In [4]:
a = next(dataloader.__iter__())

torch.Size([81369, 3])


/home/tb5zhh/SUField/sufield/datasets/transforms.py:228: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  noise_dim = ((coords - coords_min).max(0)[0] // granularity).to(int) + 3


torch.Size([81369, 3])
torch.Size([81369, 3])
torch.Size([81369, 3])
torch.Size([81369, 3])
torch.Size([45201, 3])
torch.Size([45201, 3])
torch.Size([22600, 3])
torch.Size([22600, 3])
torch.Size([22600, 3])
torch.Size([22600, 3])
torch.Size([22600, 3])
torch.Size([80583, 3])
torch.Size([80583, 3])
torch.Size([80583, 3])
torch.Size([80583, 3])
torch.Size([80583, 3])
torch.Size([31426, 3])
torch.Size([31426, 3])
torch.Size([15713, 3])
torch.Size([15713, 3])
torch.Size([15713, 3])
torch.Size([15713, 3])
torch.Size([15713, 3])
torch.Size([86001, 3])
torch.Size([86001, 3])
torch.Size([86001, 3])
torch.Size([86001, 3])
torch.Size([86001, 3])
torch.Size([20599, 3])
torch.Size([20599, 3])
torch.Size([10299, 3])
torch.Size([10299, 3])
torch.Size([10299, 3])
torch.Size([10299, 3])
torch.Size([10299, 3])
torch.Size([125526, 3])
torch.Size([125526, 3])
torch.Size([125526, 3])
torch.Size([125526, 3])
torch.Size([125526, 3])
torch.Size([24639, 3])
torch.Size([24639, 3])
torch.Size([12319, 3])
torch.

In [7]:
a

(tensor([[  0,  82,  13,  16],
         [  0,  81,  13,  14],
         [  0,  80,  13,  15],
         ...,
         [  3, 113,   3,  18],
         [  3, 119,   3,  27],
         [  3, 114,   4,  19]], dtype=torch.int32),
 tensor([[ 88.,  65.,  72.],
         [125.,  68.,  76.],
         [116., 107.,  83.],
         ...,
         [104.,  61.,  26.],
         [201., 163., 189.],
         [123.,  47.,  68.]]),
 tensor([ 13, 255,  13,  ...,   0, 255,   0], dtype=torch.int32),
 ('/home/share/datasets/SCANNET/scans/scene0000_00/scene0000_00_vh_clean_2.ply',
  '/home/share/datasets/SCANNET/scans/scene0000_01/scene0000_01_vh_clean_2.ply',
  '/home/share/datasets/SCANNET/scans/scene0000_02/scene0000_02_vh_clean_2.ply',
  '/home/share/datasets/SCANNET/scans/scene0001_00/scene0001_00_vh_clean_2.ply'),
 ('/home/share/datasets/SCANNET/scans/scene0000_00/scene0000_00_vh_clean_2.labels.ply',
  '/home/share/datasets/SCANNET/scans/scene0000_01/scene0000_01_vh_clean_2.labels.ply',
  '/home/share/dataset

In [10]:
import torch
torch.tensor(1.).dtype

torch.float32

In [1]:
from sufield.datasets import get_transform
import yaml
with open('/home/tb5zhh/SUField/config.yaml') as f:
    a = f.read()
args =  yaml.load(a, yaml.Loader)['training']
get_transform(args['transforms'])
from sufield.datasets import get_transform
import torch
transform = get_transform(args['transforms'])
a = torch.rand(8000, 3).cuda()
b = (torch.rand(8000, 3) + 3).cuda()
c = torch.rand(8000).cuda()
transform(a, b, c)

/home/tb5zhh/.conda/envs/sufield/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
/home/tb5zhh/SUField/sufield/datasets/transforms.py:230: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  noise_dim = ((coords - coords_min).max(0)[0] // granularity).to(int) + 3

torch.Size([8000, 3])
torch.Size([8000, 3])
torch.Size([8000, 3])
torch.Size([8000, 3])
torch.Size([5083, 3])
torch.Size([5083, 3])
torch.Size([2541, 3])
torch.Size([2541, 3])
torch.Size([2541, 3])
torch.Size([2541, 3])
torch.Size([2541, 3])


(tensor([[ 7, 10, 13],
         [ 5, 19, 17],
         [ 6,  3, 17],
         ...,
         [ 7,  7,  6],
         [ 3, 15, 16],
         [13,  7, 17]], device='cuda:0', dtype=torch.int32),
 tensor([[24.4992, 21.1477,  0.0000],
         [21.4620, 21.5042,  0.9064],
         [27.8408, 26.8956,  1.1982],
         ...,
         [27.5968, 24.5095,  0.0000],
         [24.0799, 24.9140,  0.0000],
         [26.8547, 25.9433,  0.2986]], device='cuda:0'),
 tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0', dtype=torch.int32))